ALTER TABLE `organization`
ADD COLUMN `code` VARCHAR(512) DEFAULT NULL COMMENT '组织机构代码' AFTER `name`,
ADD COLUMN `version` BIGINT UNSIGNED NOT NULL COMMENT '版本' AFTER `code`,
ADD COLUMN `expired_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '过期时间' AFTER `lon`;